// <auto-generated />
using System;
using LinguistPro.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinguistPro.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260208000000_AddUserPreferences")]
    partial class AddUserPreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LinguistPro.Models.UserPreferences", b =>
                {
                    b.Property<int>("PreferencesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("FontSize")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultLanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemsPerPage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableEmailNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnablePushNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableStreakReminders")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyReminderHour")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSoundNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoSaveInterval")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowPronunciationGuide")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowUsageExamples")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UILanguage")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.HasKey("PreferencesId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("LinguistPro.Models.UserPreferences", b =>
                {
                    b.HasOne("LinguistPro.Models.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("LinguistPro.Models.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
