// <auto-generated />
using System;
using LinguistPro.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinguistPro.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260207175038_AddSpacedRepetitionSystem")]
    partial class AddSpacedRepetitionSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LinguistPro.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LinguistPro.Models.DailyLearningLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemsMastered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageItemsLearned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LearningDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MasteryLevelAtEndOfDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTimeSpentSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VerbsLearned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VocabularyItemsLearned")
                        .HasColumnType("INTEGER");

                    b.HasKey("LogId");

                    b.HasIndex("LanguageProfileId", "LearningDate")
                        .IsUnique();

                    b.ToTable("DailyLearningLogs");
                });

            modelBuilder.Entity("LinguistPro.Models.LanguageItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LanguageProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastReviewed")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mastery")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsageExample")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsageExampleMeaning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageProfileId");

                    b.ToTable("LanguageItems");
                });

            modelBuilder.Entity("LinguistPro.Models.LanguageProfile", b =>
                {
                    b.Property<int>("LanguageProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MasteryLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LanguageProfileId");

                    b.HasIndex("UserId");

                    b.ToTable("LanguageProfiles");
                });

            modelBuilder.Entity("LinguistPro.Models.LearningStreak", b =>
                {
                    b.Property<int>("StreakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastLearningDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StreakStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalLearningDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("StreakId");

                    b.HasIndex("LanguageProfileId")
                        .IsUnique();

                    b.ToTable("LearningStreaks");
                });

            modelBuilder.Entity("LinguistPro.Models.ReviewSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<int>("IncorrectCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LanguageItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastReviewedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeitnerBox")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NextReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VocabularyItemId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("ScheduleId");

                    b.HasIndex("LanguageItemId")
                        .IsUnique();

                    b.HasIndex("LeitnerBox");

                    b.HasIndex("NextReviewDate");

                    b.HasIndex("VocabularyItemId")
                        .IsUnique();

                    b.ToTable("ReviewSchedules");
                });

            modelBuilder.Entity("LinguistPro.Models.UserProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("LinguistPro.Models.VerbEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Infinitive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LanguageProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P2Form")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P2Inf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("S1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("S2Form")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("S2Inf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("S3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tense")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageProfileId");

                    b.ToTable("Verbs");
                });

            modelBuilder.Entity("LinguistPro.Models.VocabularyItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LanguageProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastReviewed")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mastery")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsageExample")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsageExampleMeaning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageProfileId");

                    b.ToTable("Vocabulary");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LinguistPro.Models.DailyLearningLog", b =>
                {
                    b.HasOne("LinguistPro.Models.LanguageProfile", "LanguageProfile")
                        .WithMany("DailyLearningLogs")
                        .HasForeignKey("LanguageProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LanguageProfile");
                });

            modelBuilder.Entity("LinguistPro.Models.LanguageItem", b =>
                {
                    b.HasOne("LinguistPro.Models.LanguageProfile", "LanguageProfile")
                        .WithMany("LanguageItems")
                        .HasForeignKey("LanguageProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LanguageProfile");
                });

            modelBuilder.Entity("LinguistPro.Models.LanguageProfile", b =>
                {
                    b.HasOne("LinguistPro.Models.UserProfile", "UserProfile")
                        .WithMany("LanguageProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("LinguistPro.Models.LearningStreak", b =>
                {
                    b.HasOne("LinguistPro.Models.LanguageProfile", "LanguageProfile")
                        .WithOne("LearningStreak")
                        .HasForeignKey("LinguistPro.Models.LearningStreak", "LanguageProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LanguageProfile");
                });

            modelBuilder.Entity("LinguistPro.Models.ReviewSchedule", b =>
                {
                    b.HasOne("LinguistPro.Models.LanguageItem", "LanguageItem")
                        .WithOne("ReviewSchedule")
                        .HasForeignKey("LinguistPro.Models.ReviewSchedule", "LanguageItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LinguistPro.Models.VocabularyItem", "VocabularyItem")
                        .WithOne("ReviewSchedule")
                        .HasForeignKey("LinguistPro.Models.ReviewSchedule", "VocabularyItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LanguageItem");

                    b.Navigation("VocabularyItem");
                });

            modelBuilder.Entity("LinguistPro.Models.UserProfile", b =>
                {
                    b.HasOne("LinguistPro.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("LinguistPro.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinguistPro.Models.VerbEntry", b =>
                {
                    b.HasOne("LinguistPro.Models.LanguageProfile", "LanguageProfile")
                        .WithMany("VerbEntries")
                        .HasForeignKey("LanguageProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LanguageProfile");
                });

            modelBuilder.Entity("LinguistPro.Models.VocabularyItem", b =>
                {
                    b.HasOne("LinguistPro.Models.LanguageProfile", "LanguageProfile")
                        .WithMany("VocabularyItems")
                        .HasForeignKey("LanguageProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LanguageProfile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("LinguistPro.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("LinguistPro.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinguistPro.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("LinguistPro.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinguistPro.Models.LanguageItem", b =>
                {
                    b.Navigation("ReviewSchedule");
                });

            modelBuilder.Entity("LinguistPro.Models.LanguageProfile", b =>
                {
                    b.Navigation("DailyLearningLogs");

                    b.Navigation("LanguageItems");

                    b.Navigation("LearningStreak");

                    b.Navigation("VerbEntries");

                    b.Navigation("VocabularyItems");
                });

            modelBuilder.Entity("LinguistPro.Models.UserProfile", b =>
                {
                    b.Navigation("LanguageProfiles");
                });

            modelBuilder.Entity("LinguistPro.Models.VocabularyItem", b =>
                {
                    b.Navigation("ReviewSchedule");
                });
#pragma warning restore 612, 618
        }
    }
}
