// <auto-generated />
using System;
using LinguistPro.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinguistPro.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260207120000_AddLanguageItems")]
    partial class AddLanguageItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("LinguistPro.Models.LanguageItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastReviewed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Mastery")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsageExample")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsageExampleMeaning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LanguageItems");
                });

            modelBuilder.Entity("LinguistPro.Models.VerbEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Infinitive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P2Form")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P2Inf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("S1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("S2Form")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("S2Inf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("S3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tense")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Verbs");
                });

            modelBuilder.Entity("LinguistPro.Models.VocabularyItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastReviewed")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mastery")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsageExample")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsageExampleMeaning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vocabulary");
                });
#pragma warning restore 612, 618
        }
    }
}
