// <auto-generated />
using System;
using LinguistPro.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinguistPro.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("LinguistPro.Models.VerbEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Infinitive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P2F")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("S1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("S2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("S2F")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("S3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Verbs");
                });

            modelBuilder.Entity("LinguistPro.Models.VocabularyItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastInteraction")
                        .HasColumnType("TEXT");

                    b.Property<int>("MasteryPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceWord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetMeaning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsageExample")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vocabulary");
                });
#pragma warning restore 612, 618
        }
    }
}
