<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ReInvented.DataAccess">
      <HintPath>F:\06. ReInvented\MainProjects\SRi.XamlUIThickenerApp\ReInvented.ThickenerModelGenerator.UI\bin\x64\Debug\ReInvented.DataAccess.dll</HintPath>
    </Reference>
    <Reference Include="ReInvented.Shared">
      <HintPath>F:\06. ReInvented\MainProjects\SRi.XamlUIThickenerApp\ReInvented.ThickenerModelGenerator.UI\bin\x64\Debug\ReInvented.Shared.dll</HintPath>
    </Reference>
    <Reference Include="ReInvented.Shared.Web">
      <HintPath>F:\06. ReInvented\MainProjects\SRi.XamlUIThickenerApp\ReInvented.ThickenerModelGenerator.UI\bin\x64\Debug\ReInvented.Shared.Web.dll</HintPath>
    </Reference>
    <Reference Include="ReInvented.UI.Themes">
      <HintPath>F:\06. ReInvented\MainProjects\SRi.XamlUIThickenerApp\ReInvented.ThickenerModelGenerator.UI\bin\x64\Debug\ReInvented.UI.Themes.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
