using System;
using System.Collections.Generic;
using System.Linq;
using ReInvented.StaadPro.Interop.Entities;

namespace RakeMechanism.Geometry.Domain
{
    public enum FrameShape
    {
        Square,
        Octagonal,
        Circular
    }

    public class FrameProfile
    {
        public FrameShape Shape { get; set; }

        public double SideDimension { get; set; }

        public double Radius { get; set; }

        public double CornerOffset { get; set; }

        public bool ContinueFromVertices { get; set; }

        public bool CloseCorners { get; set; }

        public bool IsEffectivelySquare => Shape == FrameShape.Square || (Shape == FrameShape.Octagonal && CornerOffset <= 0.0001);

        public double ResolveSideDimension()
        {
            if (SideDimension > 0)
            {
                return SideDimension;
            }

            if (Radius > 0)
            {
                return Radius * Math.Sqrt(2.0);
            }

            throw new InvalidOperationException("A positive frame side dimension or radius must be provided.");
        }

        public double GetConnectivityRadius()
        {
            double side = ResolveSideDimension();
            double halfSide = side / 2.0;

            if (IsEffectivelySquare || !ContinueFromVertices)
            {
                return Math.Sqrt((halfSide * halfSide) + (halfSide * halfSide));
            }

            double offset = ClampCornerOffset(side);
            double offsetX = halfSide - offset;

            return Math.Sqrt((offsetX * offsetX) + (halfSide * halfSide));
        }

        public int GetConnectivityNodeCount()
        {
            if (IsEffectivelySquare)
            {
                return 4;
            }

            return ContinueFromVertices ? 8 : 4;
        }

        public IReadOnlyList<double> GetConnectivityAnglesDegrees()
        {
            double side = ResolveSideDimension();

            return GetConnectivityPlanPoints(side)
                .Select(point => SegmentBoundaryDefinition.NormalizeAngleDegrees(Math.Atan2(point.Z, point.X) * 180.0 / Math.PI))
                .ToArray();
        }

        public SegmentBoundaryDefinition CreateBoundaryDefinition(string description)
        {
            return new SegmentBoundaryDefinition(
                description,
                SegmentBoundaryKind.FixedFrame,
                GetConnectivityRadius(),
                GetConnectivityAnglesDegrees());
        }

        public FrameGeometry CreateFrameGeometry(double elevationY, ref int startNodeId)
        {
            if (Shape == FrameShape.Circular)
            {
                throw new InvalidOperationException("Circular frame geometry should be generated by a tube segment, not a cage frame profile.");
            }

            double side = ResolveSideDimension();
            var allNodes = new List<Node>();
            var perimeterNodes = CreatePerimeterNodes(side, elevationY, ref startNodeId);
            allNodes.AddRange(perimeterNodes);

            var cornerNodes = IsEffectivelySquare
                ? new List<Node>()
                : CreateCornerNodes(side, elevationY, ref startNodeId);

            allNodes.AddRange(cornerNodes);

            IReadOnlyList<int> connectivityIndices;

            if (IsEffectivelySquare)
            {
                connectivityIndices = Enumerable.Range(0, 4).ToArray();
            }
            else if (ContinueFromVertices)
            {
                connectivityIndices = Enumerable.Range(0, 8).ToArray();
            }
            else
            {
                connectivityIndices = Enumerable.Range(perimeterNodes.Count, cornerNodes.Count).ToArray();
            }

            return new FrameGeometry(this, allNodes, perimeterNodes, cornerNodes, connectivityIndices);
        }

        public void Validate(string context, ICollection<string> errors)
        {
            if (Shape == FrameShape.Circular)
            {
                errors.Add($"{context}: circular frame profiles are not supported inside cage segments.");
                return;
            }

            double side;

            try
            {
                side = ResolveSideDimension();
            }
            catch (InvalidOperationException ex)
            {
                errors.Add($"{context}: {ex.Message}");
                return;
            }

            if (side <= 0)
            {
                errors.Add($"{context}: the frame size must be greater than zero.");
            }

            if (Shape == FrameShape.Octagonal)
            {
                double maxOffset = side / 2.0;

                if (CornerOffset < 0)
                {
                    errors.Add($"{context}: the corner offset cannot be negative.");
                }
                else if (CornerOffset > maxOffset)
                {
                    errors.Add($"{context}: the corner offset must be less than or equal to half of the side dimension.");
                }
            }
        }

        private IReadOnlyList<(double X, double Z)> GetConnectivityPlanPoints(double side)
        {
            if (IsEffectivelySquare)
            {
                return GetSquarePlanPoints(side);
            }

            return ContinueFromVertices ? GetOctagonalPlanPoints(side) : GetSquarePlanPoints(side);
        }

        private List<Node> CreatePerimeterNodes(double side, double elevationY, ref int startNodeId)
        {
            IEnumerable<(double X, double Z)> planPoints = IsEffectivelySquare
                ? GetSquarePlanPoints(side)
                : GetOctagonalPlanPoints(side);

            return CreateNodesFromPlanPoints(planPoints, elevationY, ref startNodeId);
        }

        private List<Node> CreateCornerNodes(double side, double elevationY, ref int startNodeId)
        {
            return CreateNodesFromPlanPoints(GetSquarePlanPoints(side), elevationY, ref startNodeId);
        }

        private static List<Node> CreateNodesFromPlanPoints(IEnumerable<(double X, double Z)> planPoints, double elevationY, ref int startNodeId)
        {
            var nodes = new List<Node>();

            foreach ((double X, double Z) point in planPoints)
            {
                nodes.Add(new Node(++startNodeId, point.X, elevationY, point.Z));
            }

            return nodes;
        }

        private IReadOnlyList<(double X, double Z)> GetSquarePlanPoints(double side)
        {
            double halfSide = side / 2.0;

            return new[]
            {
                (halfSide, halfSide),
                (-halfSide, halfSide),
                (-halfSide, -halfSide),
                (halfSide, -halfSide)
            };
        }

        private IReadOnlyList<(double X, double Z)> GetOctagonalPlanPoints(double side)
        {
            double halfSide = side / 2.0;
            double offset = ClampCornerOffset(side);

            return new[]
            {
                (halfSide, halfSide - offset),
                (halfSide - offset, halfSide),
                (-halfSide + offset, halfSide),
                (-halfSide, halfSide - offset),
                (-halfSide, -halfSide + offset),
                (-halfSide + offset, -halfSide),
                (halfSide - offset, -halfSide),
                (halfSide, -halfSide + offset)
            };
        }

        private double ClampCornerOffset(double side)
        {
            if (CornerOffset <= 0)
            {
                return 0;
            }

            return Math.Min(CornerOffset, side / 2.0);
        }
    }
}
