<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net5.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="ReInvented.DataAccess">
		  <HintPath>E:\SolutionsReInvented\MainProjects\SRi.XamlUIThickenerApp\ReInvented.StaadPro.Interop.Core\bin\Debug\ReInvented.DataAccess.dll</HintPath>
		</Reference>
		<Reference Include="ReInvented.Shared">
		  <HintPath>E:\SolutionsReInvented\MainProjects\SRi.XamlUIThickenerApp\ReInvented.StaadPro.Interop.Core\bin\Debug\ReInvented.Shared.dll</HintPath>
		</Reference>
		<Reference Include="ReInvented.StaadPro.Interop">
		  <HintPath>E:\SolutionsReInvented\MainProjects\SRi.XamlUIThickenerApp\ReInvented.StaadPro.Interop.Core\bin\Debug\ReInvented.StaadPro.Interop.dll</HintPath>
		</Reference>
		<Reference Include="ReInvented.StaadPro.Interop.Core">
		  <HintPath>E:\SolutionsReInvented\MainProjects\SRi.XamlUIThickenerApp\ReInvented.StaadPro.Interop.Core\bin\Debug\ReInvented.StaadPro.Interop.Core.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>
